[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "popdynamics"
version = "0.0.1"
authors = [ "Luca Mantani" ]
description = "A framework for population dynamics"
repository = "https://github.com/LucaMantani/PopDynamics"
readme = "README.md"
packages = [{ include = "popdynamics" }]


[tool.poetry.dependencies]
python = ">=3.12"
numpy = "*"
jax = "*"
diffrax = "*"        # brings equinox, optimistix, lineax
matplotlib = "*"
pyyaml = "*"

# Mark Sphinx and its extensions optional:
sphinx = {version="*", optional=true}
sphinxcontrib-bibtex = {version="*", optional=true}
sphinx-rtd-theme = {version="*", optional=true}
tabulate = {version="*", optional=true}
sphinx-copybutton = {version="*", optional=true}


[tool.poetry.extras]
doc = ["sphinxcontrib-bibtex", "sphinx-rtd-theme", "sphinx", "tabulate", "sphinx-copybutton"]


[tool.poetry.group.dev.dependencies]
pytest = "*"


[tool.poetry.scripts]
pop-dyn = "popdynamics.cli:main"


[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning:importlib",
]
